// user-cli-menu.cpp


#include <iostream>

/*

- thinking about selections similar to:
    1. Selection 1 - power on and register smart devices which reads smart device CSV file
    2. Selection 2 - thermostat
    3. Selection 3 - TV
    4. Selection 4 - lighting
    5. Selection 5 - security system
    6. Quit

- if i have enough time maybe add some functionality to list devices and/or device info
- if i have enough time maybe make the CLI menu dynamic and generated by the devices
  read from the CSV file or something

- if i were doing this for real, i'd probably make use of IP multicast, wireless, or maybe
  bluetooth and attempt to register the smart devices with the controller if they had
  a valid license or something

- what about loading the smart devices on startup? seems like a good idea.

- can use c++ i/o file that contains latests device settings or defaults etc.

*/
void displayMenu();
void selection1();
void selection2();
void selection3();
void selection4();
void selection5();
void quit();


void menuRun()
{
    int userSelection;

    while (true)
    {
        displayMenu();
        std::cin >> userSelection;

        switch (userSelection)
        {
        case 1:
            selection1();
            break;
        case 2:
            selection2();
            break;
        case 3:
            selection3();
            break;
        case 4:
            selection4();
            break;
        case 5:
            quit();
        case 6:
            return;
        default:
            std::cout << "Invalid Selection... Please Make a Different Selection or Type \"Quit\" (\"Q\") to Exit the Menu." << std::endl;
            break;
        }
    }
}